### ISSUE TITLE
Way to filter winnowmap2 BAM files for read lengths

### ISSUE THREAD

**Issue by Musketeer-D** [timplab/T2T-Epigenetics#1]
Could I use 'samtools view -h Winnowmap.bam | awk 'length($10) > 50000 || $1 ~ /^@/' | samtools view -bS - > 50k.bam' to get winnowmap2 BAM files filtered for read lengths greater than 50 kb?  like mentioned in 'Epigenetic Patterns in a Complete Human Genome' ?

**Comment by Musketeer-D** [comment]
I didn't find the step to get BAM files filtered for read lengths ike mentioned in 'Epigenetic Patterns in a Complete Human Genome'  paper in this repositories.

**Comment by gmoneyomics** [comment]
Hi. Yes, that is exactly how we did it. Refer to line 7 here: https://github.com/timplab/T2T-Epigenetics/blob/8e66f7103e8b67eaf1b535bb90ac484553a9c3c7/methylation_calling/t2t-cpg/filter_50kb.sh#L7

**Comment by Musketeer-D** [comment]
Thank you for your kind help !
